plugins:
  - jekyll-seo-tag

title: Jack and Syl's Gourmet Sweets

description: Jack and Sly's Gourmet sweets is a home catering business bringing you authentic latin sweets.

url: http://www.jackandsyls.com
logo: /images/logo.png

social:
  name: Jack and Syl's Gourmet Sweets
  - http://www.instagram.com/jack.and.syl
  - http://www.facebook.com/Jackandsy/
